id: 04c76dc48f90485cb409c4b5fa8a8957
title: Toh_127-The_King_of_Samadhis_Sutra-v1
type: translation
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-03-26T16:03:30.805Z'
  creationid: celso
  eft-text-id: UT22084-055-001
  eft-text-version: 1.45.3 2020
  xmlns-eft: http://read.84000.co/ns/1.0
